name: CraftableHeads
version: '1.1'
main: de.adrian.craftableHeads.CraftableHeads
api-version: '1.21'
authors: [ hiadrian ]
description: Craftable Heads v1.0
commands:
  changehead:
    description: Change the heads Skin